# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1366, 839)
        self.MainFrame = QtWidgets.QFrame(parent=Form)
        self.MainFrame.setGeometry(QtCore.QRect(50, 40, 661, 691))
        self.MainFrame.setStyleSheet("QFrame{\n"
"    background-color: rgb(13, 15, 18);\n"
"    border-radius :12px;\n"
"}")
        self.MainFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.MainFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.MainFrame.setObjectName("MainFrame")
        self.MainFrame_2 = QtWidgets.QFrame(parent=self.MainFrame)
        self.MainFrame_2.setGeometry(QtCore.QRect(90, 40, 561, 631))
        self.MainFrame_2.setStyleSheet("QFrame{\n"
"    background-color: rgb(43, 45, 48);\n"
"    border-radius :12px;\n"
"}")
        self.MainFrame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.MainFrame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.MainFrame_2.setObjectName("MainFrame_2")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.MainFrame_2)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 541, 611))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.label = QtWidgets.QLabel(parent=self.page)
        self.label.setGeometry(QtCore.QRect(10, 10, 49, 16))
        self.label.setStyleSheet("QLabel{\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.label.setObjectName("label")
        self.big_button_frame = QtWidgets.QFrame(parent=self.page)
        self.big_button_frame.setGeometry(QtCore.QRect(0, 0, 541, 611))
        self.big_button_frame.setMaximumSize(QtCore.QSize(16777214, 16777215))
        self.big_button_frame.setStyleSheet("QFrame{\n"
"    background-color: rgb(43, 45, 48);\n"
"    border-radius :0px;\n"
"}\n"
"")
        self.big_button_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.big_button_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.big_button_frame.setObjectName("big_button_frame")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=self.big_button_frame)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 541, 611))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.pushButton.setMinimumSize(QtCore.QSize(150, 150))
        self.pushButton.setMaximumSize(QtCore.QSize(150, 150))
        self.pushButton.setStyleSheet("        QPushButton {\n"
"            border: 10px solid rgb(73, 85, 88);  \n"
"            border-radius: 50px;  \n"
"            background-color: transparent;  \n"
"            color: white;  \n"
"            font-size: 16px;\n"
"        }\n"
"        QPushButton:hover {\n"
"             border: 10px solid rgb(23, 25, 28); \n"
"        }\n"
"        QPushButton:pressed {\n"
"            border: 10px solid rgb(0, 0, 255); \n"
"        }\n"
"        QPushButton:checked {\n"
"            border: 10px solid rgb(0, 0, 255); \n"
"        }\n"
"        ")
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("pics/on-off-button.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(64, 64))
        self.pushButton.setCheckable(True)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.big_button_frame.raise_()
        self.label.raise_()
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.label_3 = QtWidgets.QLabel(parent=self.page_2)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 49, 16))
        self.label_3.setStyleSheet("QLabel{\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.label_3.setObjectName("label_3")
        self.frame = QtWidgets.QFrame(parent=self.page_2)
        self.frame.setGeometry(QtCore.QRect(0, 0, 541, 611))
        self.frame.setStyleSheet("QFrame{\n"
"    background-color: rgb(43, 45, 48);\n"
"    border-radius :0px;\n"
"}\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.label_14 = QtWidgets.QLabel(parent=self.frame)
        self.label_14.setGeometry(QtCore.QRect(280, 200, 111, 21))
        self.label_14.setStyleSheet("QLabel{\n"
"    background-color: rgb(43, 45, 48);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.label_14.setText("")
        self.label_14.setObjectName("label_14")
        self.layoutWidget = QtWidgets.QWidget(parent=self.frame)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 70, 331, 231))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.camera_box = QtWidgets.QComboBox(parent=self.layoutWidget)
        self.camera_box.setStyleSheet("QComboBox {\n"
"    background-color: rgb(43, 45, 48);  /* Темный фон */\n"
"    color: rgb(255, 255, 255);  /* Белый текст */\n"
"    border: 1px solid rgb(0, 0, 127);  /* Зеленая рамка */\n"
"    border-radius: 5px;\n"
"    padding: 3px;\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    background-color: #2a2b2e;  /* Более светлый фон при наведении */\n"
"    border: 1px solid #00bfff;  /* Голубая рамка при наведении */\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #1e1f22;  /* Темный фон для выпадающего списка */\n"
"    color: white;  /* Белый текст */\n"
"    selection-background-color: #3a3b3e;  /* Фон выбранного элемента */\n"
"    selection-color: #00bfff;  /* Цвет текста выбранного элемента */\n"
"    border: 1px solid rgb(0, 0, 127);  /* Зеленая рамка */\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    background-color: #1e1f22;\n"
"    border-left: 1px solid rgb(0, 0, 127);  /* Левая граница кнопки для выпадающего списка */\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(/path/to/your/arrow-icon.png);  /* Замените путь на путь к иконке стрелки, если нужно */\n"
"    width: 12px;\n"
"    height: 12px;\n"
"}")
        self.camera_box.setEditable(True)
        self.camera_box.setCurrentText("")
        self.camera_box.setObjectName("camera_box")
        self.gridLayout.addWidget(self.camera_box, 1, 1, 1, 1)
        self.select_quality = QtWidgets.QComboBox(parent=self.layoutWidget)
        self.select_quality.setStyleSheet("QComboBox {\n"
"    background-color: rgb(43, 45, 48);  /* Темный фон */\n"
"    color: rgb(255, 255, 255);  /* Белый текст */\n"
"    border: 1px solid rgb(0, 0, 127);  /* Зеленая рамка */\n"
"    border-radius: 5px;\n"
"    padding: 3px;\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    background-color: #2a2b2e;  /* Более светлый фон при наведении */\n"
"    border: 1px solid #00bfff;  /* Голубая рамка при наведении */\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #1e1f22;  /* Темный фон для выпадающего списка */\n"
"    color: white;  /* Белый текст */\n"
"    selection-background-color: #3a3b3e;  /* Фон выбранного элемента */\n"
"    selection-color: #00bfff;  /* Цвет текста выбранного элемента */\n"
"    border: 1px solid rgb(0, 0, 127);  /* Зеленая рамка */\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    background-color: #1e1f22;\n"
"    border-left: 1px solid rgb(0, 0, 127);  /* Левая граница кнопки для выпадающего списка */\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(/path/to/your/arrow-icon.png);  /* Замените путь на путь к иконке стрелки, если нужно */\n"
"    width: 12px;\n"
"    height: 12px;\n"
"}")
        self.select_quality.setEditable(True)
        self.select_quality.setCurrentText("")
        self.select_quality.setObjectName("select_quality")
        self.gridLayout.addWidget(self.select_quality, 0, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_15.setStyleSheet("QLabel{\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 3, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_4.setStyleSheet("QLabel{\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_6.setStyleSheet("QLabel{\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 0, 1, 1)
        self.show_frame = QtWidgets.QComboBox(parent=self.layoutWidget)
        self.show_frame.setStyleSheet("QComboBox {\n"
"    background-color: rgb(43, 45, 48);  /* Темный фон */\n"
"    color: rgb(255, 255, 255);  /* Белый текст */\n"
"    border: 1px solid rgb(0, 0, 127);  /* Зеленая рамка */\n"
"    border-radius: 5px;\n"
"    padding: 3px;\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    background-color: #2a2b2e;  /* Более светлый фон при наведении */\n"
"    border: 1px solid #00bfff;  /* Голубая рамка при наведении */\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #1e1f22;  /* Темный фон для выпадающего списка */\n"
"    color: white;  /* Белый текст */\n"
"    selection-background-color: #3a3b3e;  /* Фон выбранного элемента */\n"
"    selection-color: #00bfff;  /* Цвет текста выбранного элемента */\n"
"    border: 1px solid rgb(0, 0, 127);  /* Зеленая рамка */\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    background-color: #1e1f22;\n"
"    border-left: 1px solid rgb(0, 0, 127);  /* Левая граница кнопки для выпадающего списка */\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(/path/to/your/arrow-icon.png);  /* Замените путь на путь к иконке стрелки, если нужно */\n"
"    width: 12px;\n"
"    height: 12px;\n"
"}")
        self.show_frame.setEditable(True)
        self.show_frame.setCurrentText("")
        self.show_frame.setObjectName("show_frame")
        self.gridLayout.addWidget(self.show_frame, 2, 1, 1, 1)
        self.bbox_show = QtWidgets.QComboBox(parent=self.layoutWidget)
        self.bbox_show.setStyleSheet("QComboBox {\n"
"    background-color: rgb(43, 45, 48);  /* Темный фон */\n"
"    color: rgb(255, 255, 255);  /* Белый текст */\n"
"    border: 1px solid rgb(0, 0, 127);  /* Зеленая рамка */\n"
"    border-radius: 5px;\n"
"    padding: 3px;\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    background-color: #2a2b2e;  /* Более светлый фон при наведении */\n"
"    border: 1px solid #00bfff;  /* Голубая рамка при наведении */\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #1e1f22;  /* Темный фон для выпадающего списка */\n"
"    color: white;  /* Белый текст */\n"
"    selection-background-color: #3a3b3e;  /* Фон выбранного элемента */\n"
"    selection-color: #00bfff;  /* Цвет текста выбранного элемента */\n"
"    border: 1px solid rgb(0, 0, 127);  /* Зеленая рамка */\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    background-color: #1e1f22;\n"
"    border-left: 1px solid rgb(0, 0, 127);  /* Левая граница кнопки для выпадающего списка */\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(/path/to/your/arrow-icon.png);  /* Замените путь на путь к иконке стрелки, если нужно */\n"
"    width: 12px;\n"
"    height: 12px;\n"
"}")
        self.bbox_show.setEditable(True)
        self.bbox_show.setCurrentText("")
        self.bbox_show.setObjectName("bbox_show")
        self.gridLayout.addWidget(self.bbox_show, 3, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_5.setStyleSheet("QLabel{\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 0, 1, 1)
        self.frame.raise_()
        self.label_3.raise_()
        self.stackedWidget.addWidget(self.page_2)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.label_2 = QtWidgets.QLabel(parent=self.page_4)
        self.label_2.setGeometry(QtCore.QRect(20, 20, 49, 16))
        self.label_2.setStyleSheet("QLabel{\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.label_2.setObjectName("label_2")
        self.label_7 = QtWidgets.QLabel(parent=self.page_4)
        self.label_7.setGeometry(QtCore.QRect(20, 50, 81, 16))
        self.label_7.setStyleSheet("QLabel{\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.label_7.setObjectName("label_7")
        self.stackedWidget.addWidget(self.page_4)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.label_13 = QtWidgets.QLabel(parent=self.page_3)
        self.label_13.setGeometry(QtCore.QRect(30, 60, 281, 31))
        self.label_13.setStyleSheet("QLabel{\n"
"    font-size: 18pt;\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.label_13.setObjectName("label_13")
        self.label_16 = QtWidgets.QLabel(parent=self.page_3)
        self.label_16.setGeometry(QtCore.QRect(20, 120, 481, 31))
        self.label_16.setStyleSheet("QLabel{\n"
"    font-size: 18pt;\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.label_16.setObjectName("label_16")
        self.stackedWidget.addWidget(self.page_3)
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.MainFrame)
        self.pushButton_3.setGeometry(QtCore.QRect(610, 10, 41, 21))
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"    background-color: rgb(43, 45, 48);\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"    border: none;\n"
"    padding: 10px;\n"
"    background-position: left center;\n"
"    background-size: 200% 100%;\n"
"    transition: all 0.5s;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-position: right center;\n"
"    background-color: rgb(120, 0, 0)\n"
"}")
        self.pushButton_3.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("pics/close.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_3.setIcon(icon1)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.MainFrame)
        self.pushButton_4.setGeometry(QtCore.QRect(560, 10, 41, 21))
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"    background-color: rgb(43, 45, 48);\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"    border: none;\n"
"    padding: 10px;\n"
"    background-position: left center;\n"
"    background-size: 200% 100%;\n"
"    transition: all 0.5s;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-position: right center;\n"
"    background-color: rgb(0, 120, 0)\n"
"}")
        self.pushButton_4.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("pics/minus-sign.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_4.setIcon(icon2)
        self.pushButton_4.setObjectName("pushButton_4")
        self.Name_Label = QtWidgets.QLabel(parent=self.MainFrame)
        self.Name_Label.setGeometry(QtCore.QRect(80, 0, 111, 41))
        self.Name_Label.setStyleSheet("QLabel{\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.Name_Label.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.Name_Label.setScaledContents(True)
        self.Name_Label.setObjectName("Name_Label")
        self.gridLayoutWidget = QtWidgets.QWidget(parent=self.MainFrame)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 50, 52, 361))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetNoConstraint)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_9 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_9.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_9.setStyleSheet("QLabel{\n"
"    color: rgb(255, 255, 255);\n"
"    qproperty-alignment: \'AlignCenter\';\n"
"}")
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 3, 0, 1, 1)
        self.Menu_button1 = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.Menu_button1.setMinimumSize(QtCore.QSize(50, 50))
        self.Menu_button1.setMaximumSize(QtCore.QSize(50, 50))
        self.Menu_button1.setStyleSheet("QPushButton {\n"
"    background-color: rgb(43, 45, 48);\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"    border: none;\n"
"    padding: 10px;\n"
"    background-position: left center;\n"
"    background-size: 200% 100%;\n"
"    transition: all 0.5s;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-position: right center;\n"
"    background-color: rgb(0, 191, 255);\n"
"}")
        self.Menu_button1.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("pics/home-agreement.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.Menu_button1.setIcon(icon3)
        self.Menu_button1.setIconSize(QtCore.QSize(32, 32))
        self.Menu_button1.setObjectName("Menu_button1")
        self.gridLayout_2.addWidget(self.Menu_button1, 0, 0, 1, 1)
        self.Menu_button2 = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.Menu_button2.setMinimumSize(QtCore.QSize(50, 50))
        self.Menu_button2.setMaximumSize(QtCore.QSize(50, 50))
        self.Menu_button2.setStyleSheet("QPushButton {\n"
"    background-color: rgb(43, 45, 48);\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"    border: none;\n"
"    padding: 10px;\n"
"    background-position: left center;\n"
"    background-size: 200% 100%;\n"
"    transition: all 0.5s;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-position: right center;\n"
"    background-color: rgb(0, 191, 255);\n"
"}")
        self.Menu_button2.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("pics/setting-bulb.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.Menu_button2.setIcon(icon4)
        self.Menu_button2.setIconSize(QtCore.QSize(32, 32))
        self.Menu_button2.setObjectName("Menu_button2")
        self.gridLayout_2.addWidget(self.Menu_button2, 2, 0, 1, 1)
        self.Menu_button4 = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.Menu_button4.setMinimumSize(QtCore.QSize(50, 50))
        self.Menu_button4.setMaximumSize(QtCore.QSize(50, 50))
        self.Menu_button4.setStyleSheet("QPushButton {\n"
"    background-color: rgb(43, 45, 48);\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"    border: none;\n"
"    padding: 10px;\n"
"    background-position: left center;\n"
"    background-size: 200% 100%;\n"
"    transition: all 0.5s;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-position: right center;\n"
"    background-color: rgb(0, 191, 255);\n"
"}")
        self.Menu_button4.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("pics/feedback.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.Menu_button4.setIcon(icon5)
        self.Menu_button4.setIconSize(QtCore.QSize(32, 32))
        self.Menu_button4.setObjectName("Menu_button4")
        self.gridLayout_2.addWidget(self.Menu_button4, 6, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_8.setStyleSheet("QLabel{\n"
"    color: rgb(255, 255, 255);\n"
"    qproperty-alignment: \'AlignCenter\';\n"
"}")
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 1, 0, 1, 1)
        self.Menu_button3 = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.Menu_button3.setMinimumSize(QtCore.QSize(50, 50))
        self.Menu_button3.setMaximumSize(QtCore.QSize(50, 50))
        self.Menu_button3.setStyleSheet("QPushButton {\n"
"    background-color: rgb(43, 45, 48);\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"    border: none;\n"
"    padding: 10px;\n"
"    background-position: left center;\n"
"    background-size: 200% 100%;\n"
"    transition: all 0.5s;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-position: right center;\n"
"    background-color: rgb(0, 191, 255);\n"
"}")
        self.Menu_button3.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("pics/bar-chart.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.Menu_button3.setIcon(icon6)
        self.Menu_button3.setIconSize(QtCore.QSize(32, 32))
        self.Menu_button3.setObjectName("Menu_button3")
        self.gridLayout_2.addWidget(self.Menu_button3, 4, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_10.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_10.setStyleSheet("QLabel{\n"
"    color: rgb(255, 255, 255);\n"
"    qproperty-alignment: \'AlignCenter\';\n"
"}")
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 5, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_11.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_11.setStyleSheet("QLabel{\n"
"    color: rgb(255, 255, 255);\n"
"    qproperty-alignment: \'AlignCenter\';\n"
"}")
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 7, 0, 1, 1)
        self.Status = QtWidgets.QLabel(parent=self.MainFrame)
        self.Status.setGeometry(QtCore.QRect(-20, 30, 31, 401))
        self.Status.setStyleSheet("QFrame{\n"
"    background-color: rgb(43, 45, 48);\n"
"    border-radius :12px;\n"
"}")
        self.Status.setText("")
        self.Status.setObjectName("Status")
        self.Status_1 = QtWidgets.QLabel(parent=self.MainFrame)
        self.Status_1.setGeometry(QtCore.QRect(-20, 50, 31, 61))
        self.Status_1.setStyleSheet("QFrame{\n"
"    background-color: rgb(43, 45, 48);\n"
"    border-radius :12px;\n"
"}")
        self.Status_1.setText("")
        self.Status_1.setObjectName("Status_1")
        self.Status_2 = QtWidgets.QLabel(parent=self.MainFrame)
        self.Status_2.setGeometry(QtCore.QRect(-20, 140, 31, 61))
        self.Status_2.setStyleSheet("QFrame{\n"
"    background-color: rgb(43, 45, 48);\n"
"    border-radius :12px;\n"
"}")
        self.Status_2.setText("")
        self.Status_2.setObjectName("Status_2")
        self.Status_3 = QtWidgets.QLabel(parent=self.MainFrame)
        self.Status_3.setGeometry(QtCore.QRect(-20, 230, 31, 61))
        self.Status_3.setStyleSheet("QFrame{\n"
"    background-color: rgb(43, 45, 48);\n"
"    border-radius :12px;\n"
"}")
        self.Status_3.setText("")
        self.Status_3.setObjectName("Status_3")
        self.Status_4 = QtWidgets.QLabel(parent=self.MainFrame)
        self.Status_4.setGeometry(QtCore.QRect(-20, 320, 31, 61))
        self.Status_4.setStyleSheet("QFrame{\n"
"    background-color: rgb(43, 45, 48);\n"
"    border-radius :12px;\n"
"}")
        self.Status_4.setText("")
        self.Status_4.setObjectName("Status_4")
        self.label_12 = QtWidgets.QLabel(parent=self.MainFrame)
        self.label_12.setGeometry(QtCore.QRect(20, 660, 61, 20))
        self.label_12.setStyleSheet("QLabel{\n"
"    color: rgb(255, 255, 255);\n"
"    qproperty-alignment: \'AlignCenter\';\n"
"}")
        self.label_12.setObjectName("label_12")
        self.pushButton_3.raise_()
        self.pushButton_4.raise_()
        self.Name_Label.raise_()
        self.MainFrame_2.raise_()
        self.gridLayoutWidget.raise_()
        self.Status.raise_()
        self.Status_1.raise_()
        self.Status_2.raise_()
        self.Status_3.raise_()
        self.Status_4.raise_()
        self.label_12.raise_()

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Home"))
        self.label_3.setText(_translate("Form", "Settings"))
        self.label_15.setText(_translate("Form", "Отображать BBOX"))
        self.label_4.setText(_translate("Form", "Качество классификации"))
        self.label_6.setText(_translate("Form", "Отображать рамку"))
        self.label_5.setText(_translate("Form", "Идентификатор веб-камеры"))
        self.label_2.setText(_translate("Form", "Stats"))
        self.label_7.setText(_translate("Form", "In progress"))
        self.label_13.setText(_translate("Form", "quneo.vi@gmail.com\n"
""))
        self.label_16.setText(_translate("Form", "https://www.youtube.com/@vadiquneo171"))
        self.Name_Label.setWhatsThis(_translate("Form", "<html><head/><body><p><span style=\" font-size:7pt;\">Alt Control. Dataset Master</span></p></body></html>"))
        self.Name_Label.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">Alt Control</span></p></body></html>"))
        self.label_9.setToolTip(_translate("Form", "<html><head/><body><p align=\"center\">Home</p></body></html>"))
        self.label_9.setText(_translate("Form", "Settings"))
        self.label_8.setToolTip(_translate("Form", "<html><head/><body><p align=\"right\">Home</p></body></html>"))
        self.label_8.setWhatsThis(_translate("Form", "<html><head/><body><p align=\"center\">ФЫВФЫ</p></body></html>"))
        self.label_8.setText(_translate("Form", "Home"))
        self.label_10.setToolTip(_translate("Form", "<html><head/><body><p align=\"center\">Home</p></body></html>"))
        self.label_10.setText(_translate("Form", "Stats"))
        self.label_11.setToolTip(_translate("Form", "<html><head/><body><p align=\"center\">Home</p></body></html>"))
        self.label_11.setText(_translate("Form", "Feedback"))
        self.label_12.setText(_translate("Form", "beta 1.0"))
